"""
NIDS — Notification Module
Sends email and/or Slack alerts for HIGH and CRITICAL severity events.

Configuration via environment variables OR config/notification_config.json:

  Email:
    NIDS_EMAIL_ENABLED   = true
    NIDS_EMAIL_HOST      = smtp.gmail.com
    NIDS_EMAIL_PORT      = 587
    NIDS_EMAIL_USER      = your@email.com
    NIDS_EMAIL_PASSWORD  = yourpassword
    NIDS_EMAIL_FROM      = your@email.com
    NIDS_EMAIL_TO        = alert@yourdomain.com

  Slack:
    NIDS_SLACK_ENABLED   = true
    NIDS_SLACK_WEBHOOK   = https://hooks.slack.com/services/XXX/YYY/ZZZ
"""

import os
import json
import logging
import smtplib
import threading
import urllib.request
import urllib.error
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

logger = logging.getLogger('NIDS.Notifications')

CONFIG_FILE = os.path.join(
    os.path.dirname(os.path.dirname(__file__)), 'config', 'notification_config.json'
)

# Severity levels that trigger external notifications
NOTIFY_SEVERITIES = {'HIGH', 'CRITICAL'}

# Rate-limit: minimum seconds between repeated identical alerts
_RATE_LIMIT_SECONDS = 300
_last_sent = {}  # key -> last sent timestamp
_lock = threading.Lock()


# ---------------------------------------------------------------------------
# Config loading
# ---------------------------------------------------------------------------

def _load_config():
    """Load notification config from JSON file, then override with env vars."""
    cfg = {
        'email': {
            'enabled':  False,
            'host':     'smtp.gmail.com',
            'port':     587,
            'user':     '',
            'password': '',
            'from':     '',
            'to':       '',
        },
        'slack': {
            'enabled': False,
            'webhook': '',
        },
    }

    if os.path.exists(CONFIG_FILE):
        try:
            with open(CONFIG_FILE) as f:
                file_cfg = json.load(f)
            for section in ('email', 'slack'):
                cfg[section].update(file_cfg.get(section, {}))
        except Exception as e:
            logger.warning(f"Could not read notification config: {e}")

    # Environment variable overrides
    env_map = {
        'email': {
            'enabled':  ('NIDS_EMAIL_ENABLED',  lambda v: v.lower() == 'true'),
            'host':     ('NIDS_EMAIL_HOST',      str),
            'port':     ('NIDS_EMAIL_PORT',      int),
            'user':     ('NIDS_EMAIL_USER',      str),
            'password': ('NIDS_EMAIL_PASSWORD',  str),
            'from':     ('NIDS_EMAIL_FROM',      str),
            'to':       ('NIDS_EMAIL_TO',        str),
        },
        'slack': {
            'enabled': ('NIDS_SLACK_ENABLED', lambda v: v.lower() == 'true'),
            'webhook': ('NIDS_SLACK_WEBHOOK', str),
        },
    }
    for section, keys in env_map.items():
        for key, (env_var, cast) in keys.items():
            val = os.environ.get(env_var)
            if val:
                cfg[section][key] = cast(val)

    return cfg


# ---------------------------------------------------------------------------
# Rate limiting
# ---------------------------------------------------------------------------

def _is_rate_limited(key):
    with _lock:
        last = _last_sent.get(key)
        now = datetime.utcnow().timestamp()
        if last and (now - last) < _RATE_LIMIT_SECONDS:
            return True
        _last_sent[key] = now
        return False


# ---------------------------------------------------------------------------
# Email
# ---------------------------------------------------------------------------

def _send_email(cfg, subject, body):
    """Send an HTML email alert."""
    try:
        msg = MIMEMultipart('alternative')
        msg['Subject'] = subject
        msg['From']    = cfg['from'] or cfg['user']
        msg['To']      = cfg['to']

        html = f"""
        <html><body>
        <h2 style="color:#cc0000;">🚨 NIDS Security Alert</h2>
        <pre style="background:#f4f4f4;padding:12px;border-left:4px solid #cc0000;">
{body}
        </pre>
        <p style="color:#888;font-size:11px;">
            Generated by NIDS at {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC
        </p>
        </body></html>
        """
        msg.attach(MIMEText(body, 'plain'))
        msg.attach(MIMEText(html, 'html'))

        with smtplib.SMTP(cfg['host'], cfg['port'], timeout=10) as server:
            server.ehlo()
            server.starttls()
            server.login(cfg['user'], cfg['password'])
            server.sendmail(msg['From'], [msg['To']], msg.as_string())

        logger.info(f"Email alert sent to {cfg['to']}: {subject}")
    except Exception as e:
        logger.error(f"Failed to send email alert: {e}")


# ---------------------------------------------------------------------------
# Slack
# ---------------------------------------------------------------------------

def _send_slack(webhook_url, severity, message, details=None):
    """Send a Slack message via an Incoming Webhook."""
    colour_map = {
        'LOW':      '#36a64f',
        'MEDIUM':   '#ffcc00',
        'HIGH':     '#ff6600',
        'CRITICAL': '#cc0000',
    }
    colour = colour_map.get(severity, '#aaaaaa')

    fields = []
    if details:
        for k, v in details.items():
            if v is not None:
                fields.append({'title': k.replace('_', ' ').title(), 'value': str(v), 'short': True})

    payload = {
        'attachments': [{
            'color':      colour,
            'title':      f'🚨 NIDS Alert [{severity}]',
            'text':       message,
            'fields':     fields,
            'footer':     'NIDS Security System',
            'ts':         int(datetime.utcnow().timestamp()),
        }]
    }

    try:
        data = json.dumps(payload).encode('utf-8')
        req = urllib.request.Request(
            webhook_url,
            data=data,
            headers={'Content-Type': 'application/json'},
            method='POST',
        )
        with urllib.request.urlopen(req, timeout=10) as resp:
            if resp.status == 200:
                logger.info(f"Slack alert sent: [{severity}] {message[:80]}")
            else:
                logger.warning(f"Slack returned status {resp.status}")
    except urllib.error.URLError as e:
        logger.error(f"Failed to send Slack alert: {e}")
    except Exception as e:
        logger.error(f"Unexpected error sending Slack alert: {e}")


# ---------------------------------------------------------------------------
# Public interface
# ---------------------------------------------------------------------------

def send_notification(severity, message, details=None):
    """
    Send a notification if severity warrants it and rate limit allows.

    Args:
        severity (str): LOW | MEDIUM | HIGH | CRITICAL
        message  (str): Short description of the event
        details (dict): Optional extra metadata (src_ip, dst_ip, etc.)
    """
    if severity not in NOTIFY_SEVERITIES:
        return

    # Rate-limit key based on message content
    rate_key = f"{severity}:{message[:60]}"
    if _is_rate_limited(rate_key):
        logger.debug(f"Notification rate-limited: {rate_key}")
        return

    cfg = _load_config()

    body_lines = [
        f"Severity : {severity}",
        f"Time     : {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC",
        f"Message  : {message}",
    ]
    if details:
        body_lines.append("")
        for k, v in details.items():
            if v is not None:
                body_lines.append(f"  {k:<16}: {v}")
    body = "\n".join(body_lines)
    subject = f"[NIDS {severity}] {message[:80]}"

    # Send in background threads to avoid blocking packet processing
    if cfg['email']['enabled'] and cfg['email']['user'] and cfg['email']['to']:
        threading.Thread(
            target=_send_email, args=(cfg['email'], subject, body), daemon=True
        ).start()

    if cfg['slack']['enabled'] and cfg['slack']['webhook']:
        threading.Thread(
            target=_send_slack,
            args=(cfg['slack']['webhook'], severity, message, details),
            daemon=True,
        ).start()
